version: '3.7' # specify docker-compose version

# Define the services/containers to be run
services:
  ihci: #name of the first service
    image: docker_ihci # specify the directory of the Dockerfile
    ports:
        - "5000:5000" #specify ports forwarding
    links:
      - database
      - redis

  database: # name of the second service
    image: mongo # specify image to build container from
    #image: sinenomine/mongodb-s390x # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding
    volumes:
        - ./mongodb/:/data/db

  redis: 
    image: redis
    ports: 
      - "6379:6379"
    command:
      redis-server
